Throw error on connection close
onmodulus/rabbit-pubsub pull request #7
Opened 2016-10-13 19:42 UTC by musgravejw

Throw an error in subscribe method when AMQP connection is closed.

2016-10-13 19:50 UTC, theworkflow approved these changes

2016-10-13 19:53 UTC, theworkflow requested changes

2016-10-13 19:53 UTC, theworkflow commented on lib/subscribe.js
> +      conn.on('close', function (err) {
It's supposed to be `ch.on('close', fn)`

2016-10-14 15:25 UTC, jackboberg approved these changes

2016-10-17 14:43 UTC, closed without merging