Update to use standard
onmodulus/rabbit-pubsub pull request #8
Opened 2016-10-27 18:47 UTC by musgravejw

Reference:  https://github.com/onmodulus/internal/issues/208

2016-10-27 20:19 UTC, jackboberg commented on package.json
> +    "standard": "^8.5.0"
move to `devDependencies`

2016-10-27 20:19 UTC, jackboberg approved these changes

2016-10-31 13:59 UTC, jackboberg requested changes

2016-10-31 13:59 UTC, jackboberg commented on package.json
> +    "test": "standard -v && tape test",
`npm run lint && npm run unit`

2016-10-31 14:03 UTC, theworkflow requested changes

2016-10-31 14:03 UTC, theworkflow commented on package.json
> +    "node": ">=6"
This code is compatible with `node@v0.10.x` and above.

2017-07-28 20:48 UTC, jackboberg commented
duplicate #10

2017-07-28 20:48 UTC, closed without merging